language: c
env:
  global:
    - ARDUINO_IDE_VERSION="1.8.8"
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)     
script:
  - build_platform esp8266
